### ISSUE TITLE
Build Mode 2 - Docker 

### ISSUE THREAD

**Issue by fglaeser** [infinispan/dotnet-client#159] opened 2021-02-05 18:06 UTC
I' have the following error after run de `build.ps1` script..

error MSB4019: Microsoft.Cpp.Default.props not found.

The build process is expecting the file in "C:\Microsoft.Cpp.Default.props".

Any ideas?

Thanks in advanced.

**Comment by fglaeser** [comment] 2021-02-08 15:22
Hi @rigazilla, I was able to generare the nuget package using a docker image. I've put my application in a container and I have de following error.

```
System.TypeInitializationException: The type initializer for 'Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'hotrod_wrap' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhotrod_wrap: cannot open shared object file: No such file or directory
   at Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_hotrodcs(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE.SWIGExceptionHelper..ctor()
   at Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE.new_ConfigurationBuilder()
   at Infinispan.HotRod.SWIGGen.ConfigurationBuilder..ctor()
   at Infinispan.HotRod.Config.ConfigurationBuilder..ctor()
   at StreamProcessor.Services.ProcessorService.ExecuteAsync(CancellationToken stoppingToken) in c:\sandbox\eandreani\dotnet-processor\src\api\Services\ProcessorService.cs:line 43
An error ocurred: The type initializer for 'Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE' threw an exception.
```
I've also set the LD_LIBRARY_PATH to /swig/native_client/lib with the same result. Could you help me?

Thanks

**Comment by rigazilla** [comment] 2021-02-08 17:10
Hey @fglaeser good job!

Are you running on Windows?
I that case I think LD_LIBRARY_PATH doesn't work.
Native libraries must be reachable in the PATH var or placed in the application working directory.

**Comment by fglaeser** [comment] 2021-02-08 17:34
@rigazilla I've changed the title to avoid misunderstandings. I've generated the nuget in a ubuntu docker image with the netcore framework because my final application will run in a linux container, that is why I'am using the LD_LIBRARY_PATH with no luck.

**Comment by rigazilla** [comment] 2021-02-08 18:07
@fglaeser you installed both .nupkg packages? .netcore and native

**Comment by fglaeser** [comment] 2021-02-08 18:19
@rigazilla, I'am using this option.

_if HOTROD_ARCH env var is not empty an Infinispan.HotRod.$HOTROD_ARCH.nupkg containing the natives dll is produced;_

but I found the the variable should be ARCH and not HOTROD_ARCH. I've set ARCH to linux-x64, then a got a `Infinispan.HotRod.linux-x64.8.2.0-Alpha2.nupkg`, this is the only nuget that I'm using.

**Comment by fglaeser** [comment] 2021-02-08 22:28
Hi @rigazilla I will give you the complete process, perhaps you could run the same locally.

1. Clone repo master branch
2. Do some changes in to build without problems:
  - A. in buildtools/build.fsx line 11 add the following:

  ```
System.Net.ServicePointManager.SecurityProtocol <- System.Net.SecurityProtocolType.Tls12 ||| System.Net.SecurityProtocolType.Tls11
 ```

   

- B. In buildtools/helper_functions.fsx line 148, replace the current url for this:
    
   ` http://ci.infinispan.org/job/Infinispan%%20C++%%20Client/job/master/lastSuccessfulBuild/artifact/build/infinispan-hotrod-cpp-%s-RHEL-x86_64.rpm`

3.  Generate a docker image for the building process with this:
 
```dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.1

RUN apt install apt-transport-https dirmngr gnupg ca-certificates
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb https://download.mono-project.com/repo/debian stable-buster main" | tee /etc/apt/sources.list.d/mono-official-stable.list

RUN apt update && apt install -y mono-devel cpio rpm2cpio swig build-essential libsasl2-dev unzip

WORKDIR /src

CMD ["./build.sh", "Build"]
```
I've created the Dockerfile in the clone folder. Then run `docker build -t hotrodbuild:3.1 .`

4. Run the container, execute `docker run -it -v /path_to_clone:/src  hotrodbuild:3.1 /bin/bash`
5. You are now inside the container. Run `./build.sh Build` then `export ARCH=linux-x64` and finally `./build.sh QuickPack` the nuget package will be generated at /src/src/Infinispan.HotRod/bin/Infinispan.HotRod.linux-x64.8.2.0-Alpha2.nupkg

6. Here is when I add the nuget to my very basic app and then run the publish command with target runtime `linux-x64`. Then I move the publish folder to the clone_repo_folder to see the app inside the builder container. Finally run `./MyBasicApp` and I've got the following error.

``` 
ystem.TypeInitializationException: The type initializer for 'Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'hotrod_wrap' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhotrod_wrap: cannot open shared object file: No such file or directory
   at Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_hotrodcs(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE.SWIGExceptionHelper..ctor()
   at Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE.new_ConfigurationBuilder()
   at Infinispan.HotRod.SWIGGen.ConfigurationBuilder..ctor()
   at Infinispan.HotRod.Config.ConfigurationBuilder..ctor()
   at StreamProcessor.Services.ProcessorService.ExecuteAsync(CancellationToken stoppingToken) in c:\sandbox\eandreani\dotnet-processor\src\api\Services\ProcessorService.cs:line 43
An error ocurred: The type initializer for 'Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE' threw an exception.

```
7. I've also set the env var LD_LIBRARY_PATH to the application path where I see all the dll an the natives. Check the ls command of my app folder.

```
ls lib*

libhotrod.so      libhotrod_protobuf.a  libprotobuf.so.15      libprotoc.so     libprotoc.so.15.0.0
libhotrod.so.1.0  libprotobuf.so        libprotobuf.so.15.0.0  libprotoc.so.15  librdkafka.so

ls hot*

hotrod_wrap.so

```

Any Ideas if I missing something?

**Comment by rigazilla** [comment] 2021-02-09 09:29
@fglaeser I've reproduced your build environment.
looks like the installed libsasl2 is not compatible with the .rpm package (build on fedora). 
I would suggest to build a dedicated .rpm in your docker image, it should be as easy as:
```
apt-get install cmake libssl-dev valgrind libkrb5-dev libprotoc-dev rpm protobuf-compiler
git clone http://github.com/infinispan/cpp-client
cd cpp-client
mkdir build
cd build
cmake ..
cmake --build . --target build_dist
cpack -G RPM 
```
at the end of the process you'll get  a `*-DEB-x86_64.rpm` that you can use instead of the prebuilt one.

**Comment by fglaeser** [comment] 2021-02-09 14:45
Hi @rigazilla, I was able to build the cpp-client and then use it with the env var HOTROD_PREBUILT_DIR with the same result.
Any more ideas?
Thanks!!!

**Comment by rigazilla** [comment] 2021-02-09 15:16
@fglaeser, the error sounds really related to missing libraries, go into the native libraries folder and try an:
`ldd libhotrod.so.1.0`
you should see how all the .so links are resolved into the filesystem

**Comment by fglaeser** [comment] 2021-02-09 15:27
@rigazilla, I've done all the build process inside a RHEL 8 container with the same result. I've tried the ldd command and I got this  ```

libprotobuf.so.15 => not found

```

so I've added the path to the LD_LIBRARY_PATH and now is working!!!!!!!!!(No Infinispan.HotRod.SWIGGen.hotrodcsPINVOKE' error). Now I have to test the connection and the basic commands for put and get.

Thanks you very match for the support, I will back to you if I have some problems with the basic operation.

**Comment by rigazilla** [comment] 2021-02-09 15:34
Great news @fglaeser !!!!
I'm happy to have been of help.

> Thanks you very match for the support, I will back to you if I have some problems with the basic operation.

Sure, just update us even if everything works :)

**Comment by fglaeser** [comment] 2021-02-09 16:04
@rigazilla, Now I've have and issue connecting to the infinispan server.
In my docker env I have this server running:

```
 docker run -it -p 11222:11222 -p 11221:11221 -v c:/sandbox:/user-config  -e CONFIG_PATH="/user-config/config.yml" -e USER="username" -e PASS="password" -e DEBUG=true quay.io/infinispan/server:12.0.0.Final-1

```
The user-config, just enabled the memcached option, so don't worry about that.

After run my app in the container I' ve got this:

```
ERROR [TransportFactory.cpp:256] Initial ping has thrown an exception when pinging 172.17.0.3:11222 : Sasl error -4 : starting SASL negotiation
./StreamProcessor: symbol lookup error: /src/linux-x64/hotrod_wrap.so: undefined symbol: _ZN10infinispan6hotrod18TransactionManager14generateV4UUIDEv

```

My code: (I've also tried with PLAIN)

```csharp
      ConfigurationBuilder builder = new ConfigurationBuilder();
      builder
       .AddServer()
           .Host("172.17.0.3")
           .Port(11222);
         builder.Security().Authentication()
                                   .Enable()
                                   .SaslMechanism("DIGEST-MD5")
                                   .SetupCallback("username", "password", "default");
```

I did also a test against DataGrid 8.1 in OpenShift and the error was the following:

```
ERROR [TransportFactory.cpp:256] Initial ping has thrown an exception when pinging data-grid-external-rhdg-dotnetcore.apps.cluster-3997680-552a.3997680-552a.example.opentlc.com:80 : Invalid magic number. Expected 0xa1 and received 0x48
./StreamProcessor: symbol lookup error: /src/linux-x64/hotrod_wrap.so: undefined symbol: _ZN10infinispan6hotrod18TransactionManager14generateV4UUIDEv

``` 
If I have to choose, my focus is OpenShift DataGrid, that is where my app will connect and run.

Any thoughts?
Thanks

**Comment by rigazilla** [comment] 2021-02-09 16:28
> After run my app in the container I' ve got this:
> 
> ```
> ERROR [TransportFactory.cpp:256] Initial ping has thrown an exception when pinging 172.17.0.3:11222 : Sasl error -4 : starting SASL negotiation
> ./StreamProcessor: symbol lookup error: /src/linux-x64/hotrod_wrap.so: undefined symbol: _ZN10infinispan6hotrod18TransactionManager14generateV4UUIDEv
> ```
sasl needs the plugin for the method you want to use i.e. for centos `yum install cyrus-sasl-plain`

The `undefined symbol` is worrying, double check that you have removed all the downloaded native libraries

> 
> 
> I did also a test against DataGrid 8.1 in OpenShift and the error was the following:
> 
> ```
> ERROR [TransportFactory.cpp:256] Initial ping has thrown an exception when pinging data-grid-external-rhdg-dotnetcore.apps.cluster-3997680-552a.3997680-552a.example.opentlc.com:80 : Invalid magic number. Expected 0xa1 and received 0x48
> ./StreamProcessor: symbol lookup error: /src/linux-x64/hotrod_wrap.so: undefined symbol: _ZN10infinispan6hotrod18TransactionManager14generateV4UUIDEv
> ```

Infinispan doesn't work with openshift routes and plain tcp, you need to enable tls and use sni or if you want to stay on plain tcp you can expose Infinispan via NodePort or LoadBalancer.
An example of TLS/SNI setup (for java) is [here](https://infinispan.org/docs/infinispan-operator/2.0.x/operator.html#creating_caches_hotrod-caches)

**Comment by fglaeser** [comment] 2021-02-09 16:50
@rigazilla, Ok about openshift, I will try that later.

Regarding the plain plugin, you are right, I don't have that error any more. But the `undefined symbol` persist. Just to avoid problems, I've created a new container from `FROM registry.access.redhat.com/ubi8/dotnet-31-runtime:3.1` with just the plugin for cyrus and my app with the `undefined symbol` error.

Any more ideas?

Thanks

**Comment by rigazilla** [comment] 2021-02-09 18:10
@fglaeser 
this PR https://github.com/infinispan/cpp-client/pull/371
should fix the problem

**Comment by fglaeser** [comment] 2021-02-09 20:08
Hi @rigazilla, thanks a lot. Do you know how long will take to merge de PR and generate a new rpm?
Thanks

**Comment by rigazilla** [comment] 2021-02-12 16:36
@fglaeser PR has been merged

**Comment by fglaeser** [comment] 2021-02-12 17:48
Ok, thanks, I will generate a nuget with this new version and I'll give it a try. Fingers crossed!

**Comment by fglaeser** [comment] 2021-02-12 18:38
@rigazilla, same error
```
./StreamProcessor: symbol lookup error: /src/hotrod_wrap.so: undefined symbol: _ZN10infinispan6hotrod18TransactionManager14generateV4UUIDEv

```

I'am using the rpm from de ci server, do you think it is better is I buiild my own rpm? I'am using it because I've move the build process to RHEL containers. Really I'm outta options right now.

**Comment by rigazilla** [comment] 2021-02-13 16:14
@fglaeser I've run the build in docker and the wrapper seems ok:
```
root@b7f5a89f45b3:/src# ./build.sh Build
root@b7f5a89f45b3:/src# nm swig/native_client/lib/hotrod_wrap.so | grep generate
root@b7f5a89f45b3:/src# 
```

check your configuration, maybe your are running an old hotrod_wrap.

**Comment by fglaeser** [comment] 2021-02-17 14:19
@rigazilla You are right, I don't know why and old hotrod_wrap was included in the nuget package, but after replaced it, there was no error. Thanks a lot for the support. One more question, do you know hot to setup string encoding for keys in the configuration builder? For what I saw,  If I put some value using the client, the key and the value are bytearrays.
Thanks

**Closed** 2021-02-17 14:55 UTC
